### ISSUE TITLE
Password reveal button not always placed correctly

### ISSUE THREAD

**Issue by simu** [simu/passwordhasherplus#22]
After removing the dependency on jquery for the whole extension, my custom password reveal button is not always positioned correctly in relation to the password field.

Goals
* Improved placement algorithm for the reveal button

**Comment by lord2800** [comment]
I've encountered this a lot. It would be nice if this could be disabled via a setting as well--I generally don't use that button in favor of the url bar toggle.

**Comment by simu** [comment]
I haven't had much time to work on the extension recently, I'll look into adding an option to disable the reveal button, as fixing the positioning is rather harder than adding another option.

**Comment by lord2800** [comment]
I can maybe poke at it if you give me a bit of guidance on where to look.

**Comment by simu** [comment]
The button is implemented by hand using some javascript in https://github.com/simu/passwordhasherplus/blob/b9c7f7cccb742028af4760d33654d1f4e803164b/content-script.js#L57-L85

A new option can be implemented in `options.html`/`options.js` and used in `content-script.js` to not create the button by simply not calling `createMaskButton()` in `bind()`.

**Comment by lord2800** [comment]
I created https://github.com/simu/passwordhasherplus/pull/23 to have an option to disable the button and I'm working on fixing the styles to just anchor it to the bottom right corner. I just need to finish testing my changes, then I'll have a PR for that too.

**Comment by lord2800** [comment]
I created https://github.com/simu/passwordhasherplus/pull/25 to fix the button placement as well as a few other minor things. If #23 lands first, I'll have to rebase #25 to handle the new place to call `requestAnimationFrame`, otherwise I'll have to rebase #23 to do it. Either way, let me know and I'll get the other fixed up.

**Comment by simu** [comment]
@lord2800 thanks for the contributions, I'll try to have a look ASAP

**Comment by simu** [comment]
@lord2800 Sorry for the long delay, work was super busy. I've merged #23. #25 LGTM as well under the assumption that the new call site to `initAllElements` is properly updated.

**Comment by lord2800** [comment]
On it!

**Comment by simu** [comment]
While #25 and #28 improve the positioning on some pages, others still struggle, e.g. gitlab.com: 
![image](https://user-images.githubusercontent.com/393160/67988045-28d1a080-fc2f-11e9-9504-4a0bb8b4e3c4.png)
![image](https://user-images.githubusercontent.com/393160/67988116-56b6e500-fc2f-11e9-91b4-b9840b8acc90.png)

I'm going to leave this issue open for now, in case someone (or myself when I'm bored enough) can try to come up with a better way. I think what's missing is that the `content-script.js` isn't really able to react correctly when already existing elements are moved around. Maybe there's a way to subscribe on position updates for individual elements and react to those, but that's an idea for another day.

**Comment by lord2800** [comment]
I'll see what I can do! Knowing that gitlab has an issue still makes it easier for me to test out different solutions.

**Comment by simu** [comment]
Other pages which I've found where the button is still placed weird are:

* Google 
![image](https://user-images.githubusercontent.com/393160/68011931-e2a92b00-fc88-11e9-8fe0-ab71f39dbc94.png)

**Comment by lord2800** [comment]
Interesting. I explicitly tested there too. :(

**Comment by simu** [comment]
maybe my changes to make it work on my default test (https://store.steampowered.com/login/?redir=&redir_ssl=1) (cf. #28) broke it on Google again, but that just shows that it's really tricky to get this right in all cases :(
